// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV1C__RURiWRc0yHXgqhnAeCwhXfy4KmY',
    appId: '1:1022035811170:web:ca63f0ab807873332b6a3b',
    messagingSenderId: '1022035811170',
    projectId: 'khedma-a90f0',
    authDomain: 'khedma-a90f0.firebaseapp.com',
    storageBucket: 'khedma-a90f0.firebasestorage.app',
    measurementId: 'G-ZERSR110D2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACd49P-QCqV9ufROrQq4W908512q_d3T0',
    appId: '1:1022035811170:android:916b9aeeee50caa92b6a3b',
    messagingSenderId: '1022035811170',
    projectId: 'khedma-a90f0',
    storageBucket: 'khedma-a90f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA13fqDBvii486otmxFBdChrNC9A2EslDQ',
    appId: '1:1022035811170:ios:097aba2995d33c692b6a3b',
    messagingSenderId: '1022035811170',
    projectId: 'khedma-a90f0',
    storageBucket: 'khedma-a90f0.firebasestorage.app',
    iosClientId: '1022035811170-ip8hgpbjpjaifj1fu49sqldq38i4s9su.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA13fqDBvii486otmxFBdChrNC9A2EslDQ',
    appId: '1:1022035811170:ios:097aba2995d33c692b6a3b',
    messagingSenderId: '1022035811170',
    projectId: 'khedma-a90f0',
    storageBucket: 'khedma-a90f0.firebasestorage.app',
    iosClientId: '1022035811170-ip8hgpbjpjaifj1fu49sqldq38i4s9su.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV1C__RURiWRc0yHXgqhnAeCwhXfy4KmY',
    appId: '1:1022035811170:web:7cf2b998cad36fce2b6a3b',
    messagingSenderId: '1022035811170',
    projectId: 'khedma-a90f0',
    authDomain: 'khedma-a90f0.firebaseapp.com',
    storageBucket: 'khedma-a90f0.firebasestorage.app',
    measurementId: 'G-GLWT83NG25',
  );
}
